### ISSUE TITLE
【Ask for data】

### ISSUE THREAD

**Issue by dannihong** [ioansarr/mouse-cerebellum-atac#2]
Dear author,
        Thanks for your great work. I want to use your data for analysis. Can you upload the output of cellranger-aggr? The cell peak matrix and fragments files. Thanks a lot.

**Comment by ioansarr** [comment]
Thanks for the interest in our work! Our data are publicly available.
Fragment files can be found at ArrayExpress (https://www.ebi.ac.uk/arrayexpress/) under the accession numbers E-MTAB-9765 (mouse) and E-MTAB-10533 (opossum).

Cell-by-peak matrices (generated by ArchR) can be downloaded as SummarizedExperiment objects from our app at https://apps.kaessmannlab.org/mouse_cereb_atac/

Please let me know if you need something else. Good luck with your research!
