### ISSUE TITLE
conserved score and a minimum age score for each cells

### ISSUE THREAD

**Issue by fengweimin-maker** [ioansarr/mouse-cerebellum-atac#3]
Dear author,
I'm very interested in your work. Great work!
How do I get the conserved score and the minimum age for each cell after I get the ppair genome alignment from phastcons? Can you input some data for the script? Like 009_peakAnnotant.rmd script in 001_processing_and_annotation folder? Thank you very much!

Best wish,
Weimin

**Comment by ioansarr** [comment]
Hi Weimin,

Thank you for your kind words and your interest in our work.

If you are interested in the conservation scores for our cells and CREs, you can download the relevant datasets from our app: https://apps.kaessmannlab.org/mouse_cereb_atac/

If you want to repeat the analysis with your own CREs/cells, the main input for phastcons were bigwig files downloaded from UCSC: https://hgdownload.soe.ucsc.edu/goldenPath/mm10/phastCons60way/. For the age estimation, we used pairwise liftover chains also downloaded from UCSC: https://hgdownload.soe.ucsc.edu/goldenPath/mm10/liftOver/

You can use these files to get conservation estimates for your CREs (001_processing_and_annotation/009_PeakAnnotation.Rmd) and then for each cell based on its accessible intergenic CREs (001_processing_and_annotation/010_cellStats_byPeaks.Rmd).

I hope this helps. I am closing this for now but please let me know if you need more data or info.

Best wishes,

Ioannis
